---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars.yml
  tasks:
  - name: install openstack
    include_role:
      name: roles/controller
      tasks_from: update_hosts_file.yml
    when: controller
