- name: apt update
  apt:
    update_cache: yes
    name: '*'
    state: latest

- name: install common software
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - software-properties-common

- name: add ansible cloud-archive:antelope
  shell: add-apt-repository cloud-archive:antelope -y
