---
- name: install openstack-dashboard
  apt: 
    name: openstack-dashboard
    state: present
    update_cache: yes


- name: update host in openstack
  replace:
    path: /etc/openstack-dashboard/local_settings.py
    regexp: "(^ *'LOCATION'): '127.0.0.1:11211',"
    replace: "\\1: '{{controller_hostname}}:11211',"


- name: update host in openstack
  lineinfile:
    path: /etc/openstack-dashboard/local_settings.py
    line: "SESSION_ENGINE = 'django.contrib.sessions.backends.cache'"
    insertbefore: '^CACHES'


- name: update host in openstack
  lineinfile:
    path: /etc/openstack-dashboard/local_settings.py
    regexp: '^OPENSTACK_HOST.*'
    line: 'OPENSTACK_HOST = "{{controller_ip}}"'


- name: update host in openstack
  lineinfile:
    path: /etc/openstack-dashboard/local_settings.py
    regexp: '^OPENSTACK_KEYSTONE_URL.*'
    line: 'OPENSTACK_KEYSTONE_URL = "http://%s:5000/identity/v3" % OPENSTACK_HOST'

