- name: install MariaDB
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - mariadb-server
  - python3-pymysql
 

- name: mysql_secure_installation
  shell: |
    mysql -uroot -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
    mysql -uroot -e "DELETE FROM mysql.user WHERE User='';"
    mysql -uroot -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test_%' OR Db='test\_%';"
    mysql -uroot -e "FLUSH PRIVILEGES;"
 

- name: update mariadb.conf for openstack
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address.*'
    line: "bind-address = {{ controller_ip }}"
    state: present
 

- name: update mariadb.conf for openstack
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^#max_connections.*'
    insertafter: '^#max_connections.*'
    line: "max_connections = 4096"
    state: present
 

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
 
