- name: config database for neutron
  shell: |
    mysql -uroot -e "CREATE DATABASE neutron;"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{NEUTRON_DBPASS}}';"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{NEUTRON_DBPASS}}';"
    mysql -uroot -e "FLUSH PRIVILEGES;"
 

- name: create neutron user
  shell: |
    . /root/keystonerc
    openstack user create --domain default --password {{NEUTRON_PASS}} neutron >> /tmp/neutron_user_create.log  2>&1 
    openstack role add --project service --user neutron admin >> /tmp/neutron_user_create.log 2>&1 
    openstack service create --name neutron --description "OpenStack Networking Service" network >> /tmp/neutron_user_create.log  2>&1 
    openstack endpoint create --region RegionOne network public http://{{ controller_hostname}}:9696 >> /tmp/neutron_user_create.log 2>&1 
    openstack endpoint create --region RegionOne network internal http://{{ controller_hostname}}:9696 >> /tmp/neutron_user_create.log  2>&1 
    openstack endpoint create --region RegionOne network admin http://{{ controller_hostname}}:9696 >> /tmp/neutron_user_create.log  2>&1
 

- name: install neutron for controller
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - neutron-server
  - neutron-plugin-ml2
  - neutron-linuxbridge-agent
  - neutron-dhcp-agent
  - neutron-metadata-agent
  - python3-neutronclient
  - neutron-l3-agent
  - neutron-plugin-ml2 
 

- name: update /etc/neutron/metadata_agent.ini
  lineinfile:
    path: /etc/neutron/metadata_agent.ini
    insertafter: '^#nova_metadata_host =.*'
    line: 'nova_metadata_host = {{ controller_hostname }}'

- name: update /etc/neutron/metadata_agent.ini
  lineinfile:
    path: /etc/neutron/metadata_agent.ini
    insertafter: '^#metadata_proxy_shared_secret =.*'
    line: 'metadata_proxy_shared_secret = {{ METADATA_SECRET }}'

- name: restart neutron service
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - nova-api
  - neutron-server
  - neutron-linuxbridge-agent
  - neutron-dhcp-agent
 

- name: backup /etc/neutron/neutron.conf
  shell: "mv /etc/neutron/neutron.conf /etc/neutron/neutron.conf.bak"

- name: update /etc/neutron/neutron.conf
  template:
    src: templates/neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    owner: root
    group: root
    mode: 0644

- name: create neutron user
  shell: |
    . /root/keystonerc
    su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
 

- name: update /etc/neutron/plugins/ml2/ml2_conf.ini 
  template:
    src: templates/ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: root
    mode: 0644
 

- name: update /etc/neutron/metadata_agent.ini
  template:
    src: templates/metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    owner: root
    group: root
    mode: 0644
 

- name: update /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  template:
    src: templates/linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: root
    mode: 0644
 

- name: update /etc/neutron/dhcp_agent.ini
  template:
    src: templates/dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    owner: root
    group: root
    mode: 0644
 

- name: update /etc/neutron/l3_agent.ini
  template:
    src: templates/l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    owner: root
    group: root
    mode: 0644
 

