- name: install rabbitmq-server
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - rabbitmq-server
  - python3-pymysql
 

- name: rabbitmqctl add_user openstack rabbitmq
  shell: "rabbitmqctl add_user openstack {{ RABBIT_PASS }}"
 

- name: rabbitmqctl set_permissions openstack
  shell: rabbitmqctl set_permissions openstack ".*" ".*" ".*"
 

