- name: config database for keystone
  shell: |
    mysql -uroot -e "CREATE DATABASE keystone;"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{KEYSTONE_DBPASS}}';"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{KEYSTONE_DBPASS}}';"
    mysql -uroot -e "FLUSH PRIVILEGES;"
 

- name: install keystone
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - keystone
  - python3-openstackclient
  - apache2
  - libapache2-mod-wsgi-py3
  - python3-oauth2client
 

- name: update /etc/keystone/keystone.conf
  lineinfile:
    path: /etc/keystone/keystone.conf
    regexp: '^#memcache_server.*'
    line: "memcache_server = {{ controller_ip }}:11211"
    state: present
 

- name: update /etc/keystone/keystone.conf
  lineinfile:
    path: /etc/keystone/keystone.conf
    regexp: '^connection.*'
    line: "connection = mysql+pymysql://keystone:{{KEYSTONE_DBPASS}}@{{ controller_ip }}/keystone"
    state: present
 

- name: update /etc/keystone/keystone.conf
  lineinfile:
    path: /etc/keystone/keystone.conf
    line: "provider = fernet"
    insertafter: '^\[token\]'
    state: present
 

- name: populate keystone database
  shell: su -s /bin/bash keystone -c "keystone-manage db_sync" >> /tmp/keystone_db_sync.log 2>&1
 

- name: initialize fernet key

  shell: |
    keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
 

- name: bootstrap keystone
  shell: "keystone-manage bootstrap --bootstrap-password {{KEYSTONE_ADMIN_PASS}} --bootstrap-admin-url http://{{ controller_ip }}:5000/v3/ --bootstrap-internal-url http://{{ controller_ip }}:5000/v3/ --bootstrap-public-url http://{{ controller_ip }}:5000/v3/ --bootstrap-region-id RegionOne >> /tmp/keystone_bootstrap.log 2>&1"
 

- name: update /etc/apache2/apache2.conf

  lineinfile:
    path: /etc/apache2/apache2.conf
    insertafter: '^#ServerRoot.*'
    line: "ServerName {{ controller_hostname}}"
    state: present
  notify:
  - restart apache2
 

- name: create keystonerc
  template:
    src: keystonerc.j2
    dest: /root/keystonerc
    owner: root
    group: root
    mode: 0600
 

- name: update bashrc
  lineinfile:
    path: /root/.bashrc
    line: "source /root/keystonerc"
    state: present
 

- name: create project service
  shell: |
    . /root/keystonerc
    openstack project create --domain default --description "Service Project" service >> /tmp/openstack_project_create.log 2>&1
 
