- name: config database for neutron
  shell: |
    mysql -uroot -e "CREATE DATABASE neutron_ml2;"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON neutron_ml2.* TO 'neutron'@'localhost' IDENTIFIED BY '{{NEUTRON_DBPASS}}';"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON neutron_ml2.* TO 'neutron'@'%' IDENTIFIED BY '{{NEUTRON_DBPASS}}';"
    mysql -uroot -e "FLUSH PRIVILEGES;"
  when: controller|bool == true

- name: create neutron user
  shell: ". /root/keystonerc openstack user create --domain default --password {{NEUTRON_PASS}} neutron>> /tmp/neutron_user_create.log  2>&1 openstack role add --project service --user neutron admin >> /tmp/neutron_user_create.log 2>&1 openstack service create --name neutron --description \"OpenStack Networking service\" neutron >> /tmp/neutron_user_create.log  2>&1 openstack endpoint create --region RegionOne network public http://{{ controller_hostname}}:9696 >> /tmp/neutron_user_create.log 2>&1 openstack endpoint create --region RegionOne network internal http://{{ controller_hostname}}:9696 >> /tmp/neutron_user_create.log  2>&1 openstack endpoint create --region RegionOne network admin http://{{ controller_hostname}}:9696 >> /tmp/neutron_user_create.log  2>&1 "
  when: controller|bool == true

- name: install neutron for controller
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - neutron-server
  - neutron-metadata-agent
  - neutron-plugin-ml2
  - python3-neutronclient
  when: controller|bool == true

