- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart glance-registry
  service:
    name: glance-registry
    state: restarted

- name: restart glance-api
  service:
    name: glance-api
    state: restarted

- name: restart nova-api
  service:
    name: nova-api
    state: restarted

- name: restart nova-consoleauth
  service:
    name: nova-consoleauth
    state: restarted

- name: restart nova-scheduler
  service:
    name: nova-scheduler
    state: restarted

- name: restart nova-conductor
  service:
    name: nova-conductor
    state: restarted

- name: restart nova-novncproxy
  service:
    name: nova-novncproxy
    state: restarted

- name: restart placement-api
  service:
    name: placement-api
    state: restarted

- name: restart neutron-server
  service:
    name: neutron-server
    state: restarted

- name: restart neutron-linuxbridge-agent
  service:
    name: neutron-linuxbridge-agent
    state: restarted

- name: restart neutron-dhcp-agent
  service:
    name: neutron-dhcp-agent
    state: restarted

- name: restart neutron-metadata-agent
  service:
    name: neutron-metadata-agent
    state: restarted

- name: restart neutron-l3-agent
  service:
    name: neutron-l3-agent
    state: restarted

- name: restart neutron-openvswitch-agent
  service:
    name: neutron-openvswitch-agent
    state: restarted

- name: restart cinder-scheduler
  service:
    name: cinder-scheduler
    state: restarted

- name: restart cinder-api
  service:
    name: cinder-api
    state: restarted

- name: restart cinder-volume
  service:
    name: cinder-volume
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: restart rabbitmq-server
  service:
    name: rabbitmq-server
    state: restarted

- name: restart mysql
  service:
    name: mysql
    state: restarted
