---
- name: install network for compute node
  apt:
    name: neutron-linuxbridge-agent
    state: present

- name: backup neutron.conf
  shell: mv /etc/neutron/neutron.conf /etc/neutron/neutron.conf.bak
  
- name: configure neutron for compute node
  template:
    dest: /etc/neutron/neutron.conf
    src: templates/neutron.conf.j2
    owner: root
    group: root
    mode: 0644

- name: restart service
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
  - neutron-linuxbridge-agent
  - nova-compute

- name: update /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  template:
    src: templates/linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: root
    mode: 0644
  
