- name: install nova
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - nova-compute


- name: backup nova.conf
  shell: |
    mv /etc/nova/nova.conf /etc/nova/nova.conf.bak


- name: create nova.conf
  template:
    src: templates/nova.conf.j2
    dest: /etc/nova/nova.conf
    owner: nova
    group: nova
    mode: 0640



- name: install nova compute kvm
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - qemu
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - virtinst
  - cpu-checker
  - libosinfo-bin
  - nova-compute
  - nova-compute-kvm
